### PR TITLE
Report Full: fix two line wrapping bugs

### LINKED ISSUE #124: Unnecessary line wrapping with `-s`
## Describe the bug
This is a re-creation of https://github.com/squizlabs/PHP_CodeSniffer/pull/3924:

> When using `-s` along with a large `--report-width`, some lines are still wrapped despite being much shorter than the selected width.

### Code sample
```php
<?php

$x=1;
```

### Custom ruleset
N/A

### To reproduce
1. Create a file called `test.php` with the code sample above.
2. Run `phpcs -s --report-width=100000 --standard=PSR12 test.php`
3. See output displayed
```
FILE: /tmp/test/test.php
---------------------------------------------------------------------------------------------------------------
FOUND 2 ERRORS AFFECTING 1 LINE
---------------------------------------------------------------------------------------------------------------
 3 | ERROR | [x] Expected at least 1 space before "="; 0 found
   |       |     (PSR12.Operators.OperatorSpacing.NoSpaceBefore)
 3 | ERROR | [x] Expected at least 1 space after "="; 0 found
   |       |     (PSR12.Operators.OperatorSpacing.NoSpaceAfter)
---------------------------------------------------------------------------------------------------------------
PHPCBF CAN FIX THE 2 MARKED SNIFF VIOLATIONS AUTOMATICALLY
---------------------------------------------------------------------------------------------------------------
```

## Expected behavior
```
FILE: /tmp/test/test.php
---------------------------------------------------------------------------------------------------------------
FOUND 2 ERRORS AFFECTING 1 LINE
---------------------------------------------------------------------------------------------------------------
 3 | ERROR | [x] Expected at least 1 space before "="; 0 found (PSR12.Operators.OperatorSpacing.NoSpaceBefore)
 3 | ERROR | [x] Expected at least 1 space after "="; 0 found (PSR12.Operators.OperatorSpacing.NoSpaceAfter)
---------------------------------------------------------------------------------------------------------------
PHPCBF CAN FIX THE 2 MARKED SNIFF VIOLATIONS AUTOMATICALLY
---------------------------------------------------------------------------------------------------------------
```

## Versions (please complete the following information)

| | |
|-|-|
| Operating System | Debian sid
| PHP version | 8.2.12
| PHP_CodeSniffer version | 3.7.2, master
| Standard | PSR12
| Install type | Composer local

## Additional context
The problem seems to be that the four non-displaying characters (`\033[0m`) added at https://github.com/PHPCSStandards/PHP_CodeSniffer/blob/c248a92ae11e79325a1509a8eb604004d8d9cd83/src/Reports/Full.php#L139 are not accounted for when calculating `$maxErrorLength` at https://github.com/PHPCSStandards/PHP_CodeSniffer/blob/c248a92ae11e79325a1509a8eb604004d8d9cd83/src/Reports/Full.php#L69 Or, alternatively, that those four characters aren't being ignored by PHP's `wordwrap()`.

The simple fix would be to add 4 more at line 69, with the downsides that the lines of dashes would be longer than necessary and a `--report-width` that's just barely long enough (e.g. 111 for this example) would still unnecessarily wrap.

A more complex fix might be to `wordwrap()` only the message, and then manually calculate the length of the last line to decide whether to append the source directly or to append it as a new line.

## Please confirm:

- [x] I have searched the issue list and am not opening a duplicate issue.
- [x] I confirm that this bug is a bug in PHP_CodeSniffer and not in one of the external standards.
- [x] I have verified the issue still exists in the `master` branch of PHP_CodeSniffer

### PR DESCRIPTION
**Pull request by anomiex**
## Description

This is a re-creation of https://github.com/squizlabs/PHP_CodeSniffer/pull/3925:

> The first is that the ANSI escape codes applied to bold the message when `-s` is used were not being taken into account when wrapping the lines for width, causing some lines to be wrapped unnecessarily.
> 
> The second is that when lines were wrapped in the middle of a long message, the `|` characters making up the table were being bolded along with the message.

## Suggested changelog entry

* Avoid unnecessarily wrapping lines in the full report when `-s` is used.
* Fix incorrect bolding of pipes in the full report tables when `-s` is used and messages wrap.

## Related issues/external references

Fixes #124
Fixes squizlabs/PHP_CodeSniffer#3924
Closes squizlabs/PHP_CodeSniffer#3925

## Types of changes

- [x] Bug fix _(non-breaking change which fixes an issue)_
- [ ] New feature _(non-breaking change which adds functionality)_
- [ ] Breaking change _(fix or feature that would cause existing functionality to change)_
    - [ ] This change is only breaking for integrators, not for external standards or end-users.
- [ ] Documentation improvement

## PR checklist

- [x] I have checked there is no other PR open for the same change.
- [x] I have read the [Contribution Guidelines](https://github.com/PHPCSStandards/PHP_CodeSniffer/blob/master/.github/CONTRIBUTING.md).
- [x] I grant the project the right to include and distribute the code under the BSD-3-Clause license (and I have the right to grant these rights).
- [ ] I have added tests to cover my changes.
  - I see no existing tests for any of the reporting formats.
- [x] I have verified that the code complies with the projects coding standards.
- [ ] [Required for new sniffs] I have added XML documentation for the sniff.

### CODE REVIEW

**Comment by jrfnl** [comment]
@anomiex Thanks for this PR. I'm looking at it now. To keep this moving forward, could you please rebase the PR ? I made some changes to the workflows since you created this branch and it would be great to see a passing build using the current workflows.

**Review by jrfnl — COMMENTED** [review]
@anomiex Thanks for reporting this issue and your work on this patch.

I've now looked at and tested this PR extensively, including with the test code from a previous fix/iteration on this code which was merged in squizlabs/PHP_CodeSniffer#2093.

Findings:
* Your code fixes the issue, but does still contain an "off by one" error somewhere.
    This can be seen when running the test code using the exact max length:
    ```bash
    phpcs -s ./test.php --report-width=110 --standard=PSR12
    phpcs -s ./test.php --report-width=111 --standard=PSR12
    ```
    Using the first command the line for the first message will still be wrapped, while when using the second command, it won't but will have a one space difference with the delimiter line.

From https://github.com/PHPCSStandards/PHP_CodeSniffer/issues/124:
> A more complex fix might be to wordwrap() only the message, and then manually calculate the length of the last line to decide whether to append the source directly or to append it as a new line.

As I was looking at this now anyway, I've prepared an update to your fix, which does just that and surprisingly, actually simplifies the code instead of making it more complex.

If you are okay with this, I can push the update in a separate commit to this PR for you to have a look at ?

As a future iteration, I would really like to safeguard these fixes (both this one as well as the ones from squizlabs/PHP_CodeSniffer#2093) with tests, but as testing the reports is greenfields, I consider that "future scope" and not something which needs to be addressed in this PR.

I also discovered another bug while testing this fix. I will pull that as a separate PR, but wouldn't mind a review from you on that PR.

**Comment by jrfnl** [comment]
> I also discovered another bug while testing this fix. I will pull that as a separate PR, but wouldn't mind a review from you on that PR.

FYI: I've opened PR #154 for this other bug.

**Comment by anomiex** [comment]
> Using the first command the line for the first message will still be wrapped, while when using the second command, it won't but will have a one space difference with the delimiter line.

That's how the existing code works, it comes from the `- 1` at https://github.com/PHPCSStandards/PHP_CodeSniffer/blob/7fb951513b9c99b006a83129841936e419203e66/src/Reports/Full.php#L116

Try a file like this, for example:
```php
<?php

$x = TRUE;
```
```
$ vendor/bin/phpcs --report-width=83 --standard=PSR12 test.php 

FILE: /tmp/test/test.php
-----------------------------------------------------------------------------------
FOUND 1 ERROR AFFECTING 1 LINE
-----------------------------------------------------------------------------------
 3 | ERROR | [x] TRUE, FALSE and NULL must be lowercase; expected "true" but found
   |       |     "TRUE"
-----------------------------------------------------------------------------------
PHPCBF CAN FIX THE 1 MARKED SNIFF VIOLATIONS AUTOMATICALLY
-----------------------------------------------------------------------------------
```
```
$ vendor/bin/phpcs --report-width=82 --standard=PSR12 test.php 

FILE: /tmp/test/test.php
----------------------------------------------------------------------------------
FOUND 1 ERROR AFFECTING 1 LINE
----------------------------------------------------------------------------------
 3 | ERROR | [x] TRUE, FALSE and NULL must be lowercase; expected "true" but
   |       |     found "TRUE"
----------------------------------------------------------------------------------
PHPCBF CAN FIX THE 1 MARKED SNIFF VIOLATIONS AUTOMATICALLY
----------------------------------------------------------------------------------
```

> As I was looking at this now anyway, I've prepared an update to your fix, which does just that and surprisingly, actually simplifies the code instead of making it more complex.
>
> If you are okay with this, I can push the update in a separate commit to this PR for you to have a look at ?

I'll be interested to see your take on it.

**Comment by jrfnl** [comment]
> > Using the first command the line for the first message will still be wrapped, while when using the second command, it won't but will have a one space difference with the delimiter line.
> 
> That's how the existing code works, it comes from the `- 1` at
> 
> https://github.com/PHPCSStandards/PHP_CodeSniffer/blob/7fb951513b9c99b006a83129841936e419203e66/src/Reports/Full.php#L116

Good catch! I've updated my change to take that into account now.

> > As I was looking at this now anyway, I've prepared an update to your fix, which does just that and surprisingly, actually simplifies the code instead of making it more complex.
> > If you are okay with this, I can push the update in a separate commit to this PR for you to have a look at ?
> 
> I'll be interested to see your take on it.

Pushing it now.

File: src/Reports/Full.php [hunk 1]
```diff
@@ -115,36 +115,49 @@ public function generateFileReport($report, File $phpcsFile, $showSources=false,
...
 
-                        if ($k === $lastLine && $showSources === true) {
-                            $msgLine .= "\033[0m".' ('.$error['source'].')';
+                    if ($showSources === true) {
+                        $lastMsg          = $errorMsg;
+                        $startPosLastLine = strrpos($errorMsg, $paddingLine2.$beforeMsg);
+                        if ($startPosLastLine !== false) {
+                            // Message is multiline.
+                            $lastMsg = substr($errorMsg, ($startPosLastLine + strlen($paddingLine2.$beforeMsg)));
                         }
```
Comment (anomiex) [inline src/Reports/Full.php:144]: It's pretty unlikely that some message will contain something like "   |         |     ", but perhaps we should still include the leading PHP_EOL here too for good measure.

On the other hand, stripping out the `$beforeMsg` on line 143 leads to inconsistency below on line 153: if `$startPosLastLine` was `false`, 8 is correct there because the string contains both `$beforeMsg` and `$afterMsg`, but if it wasn't then we stripped off the `$beforeMsg` so only 4 are needed.
```suggestion
                        $startPosLastLine = strrpos($errorMsg, PHP_EOL.$paddingLine2.$beforeMsg);
                        if ($startPosLastLine !== false) {
                            // Message is multiline. Take just the last line (starting at the `$beforeMsg`).
                            $lastMsg = substr($errorMsg, ($startPosLastLine + strlen(PHP_EOL.$paddingLine2)));
                        }
```

Seeing the result of the inconsistency is kind of tough. Adding `$phpcsFile->addWarning( str_repeat( 'x ', 100 ) . 'x', 0, 'Test' );` in some sniff so single characters wrap can show it.

File: src/Reports/Full.php [hunk 2]
```diff
@@ -115,36 +115,49 @@ public function generateFileReport($report, File $phpcsFile, $showSources=false,
...
-                        );
-                    }
+                        // When show sources is used, the message itself will be bolded, so we need to correct the length.
+                        $sourceSuffix = '('.$error['source'].')';
+
+                        $lastMsgPlusSourceLength = strlen($lastMsg);
+                        // Add space + source suffix length.
+                        $lastMsgPlusSourceLength += (1 + strlen($sourceSuffix));
+                        // Correct for the color codes.
+                        $lastMsgPlusSourceLength -= 8;
```
Comment (anomiex) [inline src/Reports/Full.php:153]: I wonder if we should do like this.
```suggestion
                        $lastMsgPlusSourceLength -= strlen($beforeMsg.$afterMsg);
```
Disadvantage is that it has to measure the length of the string, advantage is that it won't accidentally break if someday someone changes the codes to something with a different length.

Or better might be to move the `strlen` outside of the loop (up near line 124).

**Review by anomiex — COMMENTED** [review]
Ah, `wordwrap()` already handles embedded newlines, so the code doesn't have to handle them itself. Good catch!

**Comment by jrfnl** [comment]
> Ah, `wordwrap()` already handles embedded newlines, so the code doesn't have to handle them itself. Good catch!

It does indeed, though have to admit I needed to test that out myself as well (which I did when creating the update): https://3v4l.org/7ENWc

File: src/Reports/Full.php (hunk 1 above)
Comment (jrfnl) [reply src/Reports/Full.php]: Nice catch! And yes, I agree with the bug analysis and the proposed fix. Updated.,.

File: src/Reports/Full.php (hunk 2 above)
Comment (jrfnl) [reply src/Reports/Full.php]: Agreed. Good change. Added now.

**Comment by anomiex** [comment]
> It does indeed, though I have to admit I needed to test that out myself as well (which I did when creating the update): https://3v4l.org/7ENWc

I did much the same thing! 😀 https://3v4l.org/knYT4

> As far as I'm concerned this is ready for merge. @anomiex All okay from your perspective too ?

Looks good to me too!

**Comment by jrfnl** [comment]
Thanks @anomiex !
