### PR TITLE
Squiz/StaticThisUsage: improve handling of anonymous functions

### LINKED ISSUE #1357: Squiz.Scope.StaticThisUsage false positive for Closure::bind closure inside static method
## Describe the bug

  `Squiz.Scope.StaticThisUsage` reports `$this` used inside a closure defined within a static method, even when that closure is explicitly bound to an object via `Closure::bind()` before being invoked.

  At runtime, $this in the closure refers to the bound object (`$newThis`), so no runtime error occurs. The sniff appears to treat $this inside the nested closure as if it was used in the static method scope.

### Code sample

```php
  <?php declare(strict_types=1);

  final class Target
  {
      public $x = 2;
  }

  final class Repro
  {
      public static function run(): void
      {
          $target = new Target();

          \Closure::bind(
              function (): void {
                  $this->x = 1; // Usage of "$this" in static methods will cause runtime errors 
              },
              $target,
              Target::class,
          )();
      }
  }
```

  ### Custom ruleset

```xml
  <?xml version="1.0"?>
  <ruleset name="Repro">
    <rule ref="Squiz.Scope.StaticThisUsage"/>
  </ruleset>
```

  ### To reproduce

  1. Create test.php with the code sample above
  2. Create ruleset.xml with the custom ruleset above
  3. Run phpcs -s --standard=ruleset.xml test.php
  4. See error message displayed

```
  ----------------------------------------------------------------------
  FOUND 1 ERROR AFFECTING 1 LINE
  ----------------------------------------------------------------------
   16 | ERROR | Usage of "$this" in static methods will cause runtime errors (Squiz.Scope.StaticThisUsage.Found)
  ----------------------------------------------------------------------
```

  ## Expected behavior

  No error

  ## Versions 

  |                             |                                                                            |
  |-----------------------------|----------------------------------------------------------------------------|
  | Operating System            | Ubuntu 24.04.3 LTS                                                         |
  | PHP version                 | 8.4.15                                  |
  | PHP_CodeSniffer version     | 4.0.1                                                                      |
  | Standard                    | Squiz                                                                       |
  | Install type                | Composer (local dev dependency)                                            |

  ## Please confirm

  - [x] I have searched the issue list and am not opening a duplicate issue.
  - [x] I have read the Contribution Guidelines and this is not a support question.
  - [x] I confirm that this bug is a bug in PHP_CodeSniffer and not in one of the external standards.
  - [ ] I have verified the issue still exists in the 4.x branch of PHP_CodeSniffer.

### PR DESCRIPTION
**Pull request by jrfnl**
# Description

### Squiz/StaticThisUsage: always skip nested anonymous scope 

As things were, the `Squiz.Scope.StaticThisUsage` sniff already skipped over the body of anonymous classes when found within the body of a static OO method, to prevent false positives related to `$this` when it refers to the anonymous class.
However, the sniff did not skip over the body of an anonymous function (closure).

This is wrong, as anonymous functions can be bound to an object, in which case the closure has access to that object via `$this`.
However, whether the object is actually bound or not, is irrelevant. The closure has its own (closed) scope and doesn't have access to variables from outside the closure, so any usages of `$this` _within_ the closure would not be the "static this usage" this sniff is looking for anyway.

With that in mind, the sniff should skip over the body of closures, same as it skips over the body of anonymous classes.

Having said that, I also believe that the sniff should explicitly examine `static` closures for the use of `$this`, while it currently doesn't (false negative), but that's another matter.

Fixes #1357

Related to previous iterations:
* squizlabs/PHP_CodeSniffer#1747 - solved via 8ad3826
* squizlabs/PHP_CodeSniffer#2725

### Squiz/StaticThisUsage: examine the body of static closures 

As noted in the previous commit, closures can be declared as `static`, in which case they do not have access to `$this`.

That case was so far not considered by this sniff.

This commit changes the sniff to:
1. Also examine `T_CLOSURE` tokens.
2. Examine these when nested inside OO methods, as well as when found completely outside of OO structures.

Note: in a future iteration it should be considered to get rid of the implementation via the `AbstractScopeSniff` as that implementation actually makes the sniff _more complicated_ instead of _less complicated_.

Includes unit tests.

### Squiz/StaticThisUsage: add extra test 

... for code in the sniff previously not covered by tests.

## Suggested changelog entry
* Fixed: Squiz.Scope.StaticThisUsage: false positive for usage of `$this` in non-static closures nested in OO methods.
* Changed: Squiz.Scope.StaticThisUsage: the sniff will now also search for the use of `$this` in `static` closures.

### CODE REVIEW

File: src/Standards/Squiz/Sniffs/Scope/StaticThisUsageSniff.php [hunk 1]
```diff
@@ -78,21 +84,25 @@ public function processTokenWithinScope(File $phpcsFile, int $stackPtr, int $cur
      * @param \PHP_CodeSniffer\Files\File $phpcsFile The current file being scanned.
      * @param int                         $next      The position of the next token to check.
      * @param int                         $end       The position of the last token to check.
+     * @param string                      $type      Either 'method' or 'closure'.
```
Comment (rodrigoprimo) [inline src/Standards/Squiz/Sniffs/Scope/StaticThisUsageSniff.php]: Nitpick:

```suggestion
     * @param string                      $type      Either 'methods' or 'closures'.
```

**Review by rodrigoprimo — COMMENTED** [review]
Looks good to me. I just left a comment with a small fix in a docblock.

File: src/Standards/Squiz/Sniffs/Scope/StaticThisUsageSniff.php (hunk 1 above)
Comment (jrfnl) [reply src/Standards/Squiz/Sniffs/Scope/StaticThisUsageSniff.php]: Thanks for catching that. To be honest, I think the docblock is correct and I need to fix the parameter being passed (as the `checkThisUsage()` method only checks one method or closure at a time).

Comment (jrfnl) [reply src/Standards/Squiz/Sniffs/Scope/StaticThisUsageSniff.php]: Fixed in https://github.com/PHPCSStandards/PHP_CodeSniffer/pull/1377/commits/bb14224ea61fdc109f5d34479e78d9a66e30e461

**Review by rodrigoprimo — APPROVED** [review]

**Comment by jrfnl** [comment]
Squashed the "fix up" commit from the review into the canonical commit it belongs with.
