### PR TITLE
[4.0] Fix exit code when phpcbf is processing STDIN

### LINKED ISSUE #1082: Use the scan exit codes when fixing code provided via STDIN
PR #1079 originally included a commit to also use the new `ExitCode::calculate()` method when the fixer runs over code provided via STDIN.

Unfortunately, that didn't work as intended, so for now, `phpcbf` will always return with a `0` exit code when ran over code provided via STDIN.

It should be investigated why the patch didn't work as expected and a fix to start using the proper exit code should be pulled.
Preferably such a patch should be accompanied by a set of tests covering the change, though creating these tests may not be that straight-forward as `STDIN` would need to be manipulated.

Also see: https://github.com/PHPCSStandards/PHP_CodeSniffer/pull/1079#discussion_r2075640077

For reference, this is the patch file of the originally proposed change:

<details>
  <summary>Patch file contents</summary>

```patch
From dc2352fe50bac97cc9a1648589619d1a4d64373e Mon Sep 17 00:00:00 2001
From: jrfnl <jrfnl@users.noreply.github.com>
Date: Tue, 29 Apr 2025 01:57:34 +0200
Subject: [PATCH] Use the new exit codes when scanning code from STDIN

---
 src/Reports/Cbf.php | 46 +++++++++++++++++++++++++++++++++++++++++++--
 1 file changed, 44 insertions(+), 2 deletions(-)

diff --git a/src/Reports/Cbf.php b/src/Reports/Cbf.php
index 823ed14a57..5a157b6e77 100644
--- a/src/Reports/Cbf.php
+++ b/src/Reports/Cbf.php
@@ -7,7 +7,9 @@
  * report from the command line.
  *
  * @author    Greg Sherwood <gsherwood@squiz.net>
+ * @author    Juliette Reinders Folmer <phpcs_nospam@adviesenzo.nl>
  * @copyright 2006-2015 Squiz Pty Ltd (ABN 77 084 670 600)
+ * @copyright 2025 PHPCSStandards and contributors
  * @license   https://github.com/PHPCSStandards/PHP_CodeSniffer/blob/master/licence.txt BSD Licence
  */
 
@@ -15,6 +17,7 @@ namespace PHP_CodeSniffer\Reports;
 
 use PHP_CodeSniffer\Exceptions\DeepExitException;
 use PHP_CodeSniffer\Files\File;
+use PHP_CodeSniffer\Reporter;
 use PHP_CodeSniffer\Util\ExitCode;
 use PHP_CodeSniffer\Util\Timing;
 use PHP_CodeSniffer\Util\Writers\StatusWriter;
@@ -60,8 +63,12 @@ class Cbf implements Report
             // Replacing STDIN, so output current file to STDOUT
             // even if nothing was fixed. Exit here because we
             // can't process any more than 1 file in this setup.
-            $fixedContent = $phpcsFile->fixer->getContents();
-            throw new DeepExitException($fixedContent, ExitCode::OKAY);
+            echo $phpcsFile->fixer->getContents();
+
+            // Fake a Reporter instance to allow for getting a proper exit code.
+            $reporter = $this->createReporterInstance($phpcsFile);
+
+            throw new DeepExitException('', ExitCode::calculate($reporter));
         }
 
         if ($errors === 0) {
@@ -246,4 +253,39 @@ class Cbf implements Report
     }//end generate()
 
 
+    /**
+     * Create a "fake" Reporter instance to allow for getting a proper exit code when scanning code provided via STDIN.
+     *
+     * @param \PHP_CodeSniffer\Files\File $phpcsFile The file being reported on.
+     *
+     * @return \PHP_CodeSniffer\Reporter
+     */
+    private function createReporterInstance(File $phpcsFile)
+    {
+        $reporter = new class extends Reporter {
+
+
+            /**
+             * Overload the constructor as we don't need it.
+             */
+            public function __construct()
+            {
+            }//end __construct()
+
+
+        };
+
+        $reporter->totalFiles           = 1;
+        $reporter->totalErrors          = $phpcsFile->getErrorCount();
+        $reporter->totalWarnings        = $phpcsFile->getWarningCount();
+        $reporter->totalFixableErrors   = $phpcsFile->getFixableErrorCount();
+        $reporter->totalFixableWarnings = $phpcsFile->getFixableWarningCount();
+        $reporter->totalFixedErrors     = $phpcsFile->getFixedErrorCount();
+        $reporter->totalFixedWarnings   = $phpcsFile->getFixedWarningCount();
+
+        return $reporter;
+
+    }//end createReporterInstance()
+
+
 }//end class
```
</details>

### PR DESCRIPTION
**Pull request by fredden**
# Description
When running `phpcbf` with a PHP file as input (eg, `phpcbf < test.php`), the exit code was not reported correctly. This pull request fixes that bug. For more details, see #1082.

## Suggested changelog entry
Fixed exit code when phpcbf is processing STDIN

## Related issues/external references

Fixes #1082

## Types of changes

- [x] Bug fix _(non-breaking change which fixes an issue)_
- [ ] New feature _(non-breaking change which adds functionality)_
- [ ] Breaking change _(fix or feature that would cause existing functionality to change)_
    - [ ] This change is only breaking for integrators, not for external standards or end-users.
- [ ] Documentation improvement

## PR checklist

- [x] I have checked there is no other PR open for the same change.
- [x] I have read the [Contribution Guidelines](https://github.com/PHPCSStandards/PHP_CodeSniffer/blob/master/.github/CONTRIBUTING.md).
- [x] I grant the project the right to include and distribute the code under the BSD-3-Clause license (and I have the right to grant these rights).
- [x] I have added tests to cover my changes.
- [x] I have verified that the code complies with the projects coding standards.
- [ ] \[Required for new sniffs\] I have added XML documentation for the sniff.
- [ ] I have opened a sister-PR in the [documentation repository](https://github.com/PHPCSStandards/PHP_CodeSniffer-documentation) to update the Wiki.

### CODE REVIEW

**Comment by fredden** [comment]
@jrfnl how would you like to cover this change with tests?

**Comment by jrfnl** [comment]
> how would you like to cover this change with tests?

I imagine it may be difficult to cover this change via the PHPUnit setup as it would require mocking `STDIN`. How about adding some tests to the `bashunit` E2E testsuite ?

**Comment by jrfnl** [comment]
@fredden Just checking - will you have time over the next few days to add a few bashunit tests for STDIN handling ? Or would you like me to add something ?

**Comment by fredden** [comment]
I'm happy to update this, but I'm away at the moment. Earliest that I can pick this up again would be Wednesday/Thursday this week. I do have a bash script that I used for local development which will be trivial to convert into the format needed for bashunit.

If you want to land this before Friday, feel free to add some tests.

File: tests/EndToEnd/phpcbf_test.sh [hunk 1]
```diff
@@ -43,3 +43,39 @@ function test_phpcbf_bug_1112() {
...
 }
+
+function test_phpcbf_exit_code_clean() {
+  bin/phpcbf --suffix=.fixed --standard=tests/EndToEnd/Fixtures/endtoend.xml.dist tests/EndToEnd/Fixtures/ClassOneWithoutStyleError.inc
+  assert_exit_code 0
+
+  # Same result via STDIN
+  bin/phpcbf --suffix=.fixed --standard=tests/EndToEnd/Fixtures/endtoend.xml.dist < tests/EndToEnd/Fixtures/ClassOneWithoutStyleError.inc
+  assert_exit_code 0
+}
```
Comment (jrfnl) [inline tests/EndToEnd/phpcbf_test.sh:54]: I've just been having a play with this and I believe it would be prudent to split each of these test methods into two separate test methods:
1. The first (normal) command + check the exit code.
2. The command with STDIN + check the exit code.

Reason being, is that if either of the assertions would fail, the resulting error message would be the same, so we have no way of knowing which of the two assertions failed.

To demonstrate, this would be the output from the new tests if the fix was removed:
image
... which doesn't give any clue as to whether the exit code setting is broken completely or only for STDIN.

I imagine, we could even consider moving these tests into separate test scripts too (`phpcs_exitcodes_test.sh` and `phpcbf_exitcodes_test.sh`).

**Review by jrfnl — COMMENTED** [review]
@fredden Thanks for adding the tests! I've had a play with this and left some feedback inline. Not necessarily blocking. We could decide to merge this now and iterate on organizing the bashunit tests in a future PR.

File: tests/EndToEnd/phpcbf_test.sh (hunk 1 above)
Comment (fredden) [reply tests/EndToEnd/phpcbf_test.sh:54]: If you're open to having additional files in this directory, then I'd like to put all these exit code tests in a single file of their own.
I'll get that sorted in the next few days.

Comment (jrfnl) [reply tests/EndToEnd/phpcbf_test.sh:54]: I see no reason to limit the tests in that directory to just the current files, so, yes please ♥️ 

I think the original tests were split into two files because `phpcbf` needs a `tear_down()` method, while `phpcs` does not, but running that `tear_down()` after a `phpcs` run shouldn't do any harm, so one file for these tests could work.

**Review by jrfnl — APPROVED** [review]
@fredden Thank you for working on this and the updates! Glad that this will be sorted before the release. 👍🏻
