### PR TITLE
Generic/Syntax: add support for inspecting code passed via STDIN

### LINKED ISSUE #915: `Generic.PHP.Syntax` false negative when file content passed via STDIN
## Describe the bug

The `Generic.PHP.Syntax` sniff is unable to check for syntax errors when the file content is passed via STDIN, resulting in a false negative.

### To reproduce
1. Run `echo '<?php $array = [1, 2, 3; // Missing closing bracket.' | phpcs --standard=Generic --sniffs=Generic.PHP.Syntax -`
3. No errors are displayed.

## Expected behavior

I believe the command above should display an error as there is a syntax error in the provided PHP code (missing closing bracket).

## Additional information

This is happening because the sniff does not consider that `$phpcsFile->getFilename()` might return `STDIN` instead of a file name:

https://github.com/PHPCSStandards/PHP_CodeSniffer/blob/dd80edb4e91e58b2bb423d361ec8281aef44cfa6/src/Standards/Generic/Sniffs/PHP/SyntaxSniff.php#L59-L60

When `STDIN` is passed to the `php -l` command, PHP returns an error saying that the file does not exist, and the sniff ends its execution without generating an error.

I think the sniff could be modified to run a different command when the file content is passed via STDIN (I'm not sure if this would work on Windows):

```
echo '<?php $array = [1, 2, 3; // Missing closing bracket.' | /usr/bin/php7.4 -l -d display_errors=1 -d error_prepend_string='' 2>&1
```

## Versions (please complete the following information)

|                                       |                                                                                                           |
|--------------------------|----------------------------------------------------------------------  |
| Operating System           | Linux                                                       |
| PHP version                    | 8.3                                                                                     |
| PHP_CodeSniffer version | master                                                                            |
| Standard                         | Generic                                                      |
| Install type                      | git clone |

## Please confirm

- [x] I have searched the issue list and am not opening a duplicate issue.
- [x] I have read the [Contribution Guidelines](https://github.com/PHPCSStandards/PHP_CodeSniffer/blob/master/.github/CONTRIBUTING.md) and this is not a [support question](https://github.com/PHPCSStandards/PHP_CodeSniffer/discussions).
- [x] I confirm that this bug is a bug in PHP_CodeSniffer and not in one of the external standards.
- [x] I have verified the issue still exists in the `master` branch of PHP_CodeSniffer.

### PR DESCRIPTION
**Pull request by rodrigoprimo**
# Description

This PR improves the `Generic.PHP.Syntax` sniff to make it work when code is passed via STDIN. Before, any code passed this way would cause a false negative as the sniff was not taking into account that `$phpcsFile->getFilename()` might return `STDIN` instead of an actual file name.

Refer to #915 for additional context and testing instructions.

## Suggested changelog entry

Fixed: the `Generic.PHP.Syntax` sniff now handles code passed via `STDIN` correctly

## Related issues/external references

Fixes #915

## Types of changes

- [x] Bug fix _(non-breaking change which fixes an issue)_
- [ ] New feature _(non-breaking change which adds functionality)_
- [ ] Breaking change _(fix or feature that would cause existing functionality to change)_
    - [ ] This change is only breaking for integrators, not for external standards or end-users.
- [ ] Documentation improvement

## PR checklist

- [x] I have checked there is no other PR open for the same change.
- [x] I have read the [Contribution Guidelines](https://github.com/PHPCSStandards/PHP_CodeSniffer/blob/master/.github/CONTRIBUTING.md).
- [x] I grant the project the right to include and distribute the code under the BSD-3-Clause license (and I have the right to grant these rights).
- [x] I have added tests to cover my changes.
- [x] I have verified that the code complies with the projects coding standards.
- [ ] \[Required for new sniffs\] I have added XML documentation for the sniff.

### CODE REVIEW

**Comment by jrfnl** [comment]
@rodrigoprimo I believe there is still something wrong in the command as the tests do not pass on Windows.

Aside from that, could you please rebase this branch on the current `master` ?

**Comment by rodrigoprimo** [comment]
> Aside from that, could you please rebase this branch on the current master ?

I just rebased without changes, and now `remark` is passing.

> @rodrigoprimo I believe there is still something wrong in the command as the tests do not pass on Windows.

I will take a look to understand why the tests are failing on Windows. When I was creating this PR, I checked that the `Quicktest` workflow was passing, but I completely forgot that the full test suite is not executed on Windows in this workflow.

**Comment by rodrigoprimo** [comment]
@jrfnl, I added the `@group Windows` to the new test and fixed the issue on Windows.

As far as I could research, it is not straightforward to reliably pipe commands and escape characters when echoing on Windows, so I opted to create a temporary file instead when on this OS, and the file content is passed via `STDIN`. What do you think of this approach?

**Comment by rodrigoprimo** [comment]
Good point, I failed to consider that PHPCS currently doesn't support `STDIN` on Windows. I went ahead, kept the original commit, dropped the two that I had added to make the sniff work when handling `STDIN` on Windows, and added a new one to skip the `STDIN` test on this OS.

File: src/Standards/Generic/Sniffs/PHP/SyntaxSniff.php [hunk 1]
```diff
@@ -72,4 +71,25 @@ public function process(File $phpcsFile, $stackPtr)
     }//end process()
 
 
+    /**
+     * Returns the command used to lint PHP code. Uses a different command when the content is
+     * provided via STDIN.
```
Comment (jrfnl) [inline src/Standards/Generic/Sniffs/PHP/SyntaxSniff.php:76]:
```suggestion
     * Returns the command used to lint PHP code.
     *
     * Uses a different command when the content is provided via STDIN.
```

File: src/Standards/Generic/Tests/PHP/SyntaxUnitTest.php [hunk 2]
```diff
@@ -60,4 +63,107 @@ public function getWarningList()
     }//end getWarningList()
 
 
+    /**
+     * Test the sniff checks syntax when file contents are passed via STDIN. Doesn't run on Windows
+     * as PHPCS currently doesn't support STDIN on this OS.
```
Comment (jrfnl) [inline src/Standards/Generic/Tests/PHP/SyntaxUnitTest.php:68]:
```suggestion
     * Test the sniff checks syntax when file contents are passed via STDIN.
     *
     * Note: this test doesn't run on Windows as PHPCS currently doesn't support STDIN on this OS.
```

**Review by jrfnl — APPROVED** [review]
Thanks for these updates @rodrigoprimo ! LGTM. Will merge once the build has passed.
