### PR TITLE
Squiz/VariableComment: allow union and intersection types to be detected

### LINKED ISSUE #178: Squiz/VariableComment: incorrectly flags missing docblock for properties with union/intersection type
## Describe the bug

When scanning a class containing properties with PHP native union or intersection types, these will always be flagged as not having a docblock even when a docblock is present.

### Code sample
```php
class Foo
{
    /**
     * This is fine.
     *
     * @var string|integer
     */
    public $correct_not_missing_docblock_union;

    /**
     * This snippet gets flagged with "Missing member variable doc comment (Squiz.Commenting.VariableComment.Missing)"
     *
     * @var string|integer
     */
    public string|int $BUG_missing_docblock_with_union_type;

    /**
     * This is fine
     *
     * @var InterfaceA&InterfacB
     */
    public $correct_not_missing_docblock_intersection;

    /**
     * This snippet gets flagged with "Missing member variable doc comment (Squiz.Commenting.VariableComment.Missing)"
     *
     * @var InterfaceA&InterfacB
     */
    public InterfaceA&InterfacB $BUG_missing_docblock_intersection;
}
```

### To reproduce
1. Create a file called `test.php` with the code sample above...
2. Run `phpcs test.php --standard=squiz --sniffs=squiz.commenting.variablecomment`
3. See error message displayed
```
---------------------------------------------------------------------------------------------
FOUND 2 ERRORS AFFECTING 2 LINES
---------------------------------------------------------------------------------------------
 17 | ERROR | Missing member variable doc comment (Squiz.Commenting.VariableComment.Missing)
 31 | ERROR | Missing member variable doc comment (Squiz.Commenting.VariableComment.Missing)
---------------------------------------------------------------------------------------------
```

## Expected behavior
That the docblocks would be recognized correctly and no "missing docblock" errors would be thrown.

## Versions (please complete the following information)

| | |
|-|-|
| Operating System | _not relevant_
| PHP version | _not relevant_
| PHP_CodeSniffer version | `master`
| Standard | Squiz
| Install type | git clone

## Additional context
PR squizlabs/PHP_CodeSniffer#3757 may contain a partial fix for this.

## Please confirm:

- [x] I have searched the issue list and am not opening a duplicate issue.
- [x] I confirm that this bug is a bug in PHP_CodeSniffer and not in one of the external standards.
- [x] I have verified the issue still exists in the `master` branch of PHP_CodeSniffer.

### PR DESCRIPTION
**Pull request by fcool**
If one uses a union type for an object property, the doc-type-hint could not be related to the variable type.

Fixed now.

Includes unit test.

This is a continuation of [#3757](https://github.com/squizlabs/PHP_CodeSniffer/pull/3757)

Closes #178
Closes squizlabs/PHP_CodeSniffer#3757

### CODE REVIEW

**Comment by fcool** [comment]
I do not understand why the tests are failing - they are not locally  - and I did not change anything regarding to alignment... so I would not expect any changes there...

File: src/Standards/Squiz/Sniffs/Commenting/VariableCommentSniff.php [hunk 1]
```diff
@@ -40,6 +40,8 @@ public function processMemberVar(File $phpcsFile, $stackPtr)
             T_STRING       => T_STRING,
             T_NS_SEPARATOR => T_NS_SEPARATOR,
             T_NULLABLE     => T_NULLABLE,
+            T_TYPE_UNION   => T_TYPE_UNION,
+            T_TYPE_INTERSECTION   => T_TYPE_INTERSECTION,
```
Comment (fredden) [inline src/Standards/Squiz/Sniffs/Commenting/VariableCommentSniff.php:44]: The coding standard used for this repository requires that equal signs line up vertically within a block. See also https://github.com/PHPCSStandards/PHP_CodeSniffer/issues/155#issuecomment-1867663412

Comment (fcool) [reply src/Standards/Squiz/Sniffs/Commenting/VariableCommentSniff.php]: Ah... Damn! I should have been able to see this myself. Thanks a lot for your super prompt and helpful suggestion

File: src/Standards/Squiz/Tests/Commenting/VariableCommentUnitTest.inc [hunk 2]
```diff
@@ -402,3 +402,19 @@ class ReadOnlyProps
...
+     */
+    private array|bool $variableName = array();
+}
+
+class IntersectionTypes
+{
+    /**
+     * @var \Iterator|\Countable
+     */
+    private \Iterator&\Countable $variableName;
```
Comment (fredden) [inline src/Standards/Squiz/Tests/Commenting/VariableCommentUnitTest.inc:419]: The comment says `|` but the code says `&`. Is this intentional?

Comment (fcool) [reply src/Standards/Squiz/Tests/Commenting/VariableCommentUnitTest.inc:419]: There is a difference between type hinting and doc types. As far as I know there is (currently) no such thing like intersection types, when it comes to doc-types

Comment (jrfnl) [reply src/Standards/Squiz/Tests/Commenting/VariableCommentUnitTest.inc:419]: I'm fine with the doctype as it is. After all, this test is _not_ about the type used in the docblock, but about the docblock not being found when PHP native union/intersection types are being used.

**Review by jrfnl — APPROVED** [review]
@fcool Thank you for porting this PR over! All looks good to me. This fix will be included in the next release.
